CREATE TABLE usuario
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome               VARCHAR(255),
    data_de_nascimento VARCHAR(255),
    cpf                VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_cpf UNIQUE (cpf);