CREATE TABLE endereco
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logradouro  VARCHAR(255),
    numero      VARCHAR(255),
    complemento VARCHAR(255),
    bairro      VARCHAR(255),
    cep         VARCHAR(255),
    cidade      VARCHAR(255),
    estado      VARCHAR(255),
    usuario_id  INT,
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);

ALTER TABLE endereco
    ADD CONSTRAINT FK_ENDERECO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);